exports_files([
    "antora-playbook.yml",
    "package.json",
    "package-lock.json",
])

filegroup(
    name = "bourbon_ui_srcs",
    srcs = glob([
        "bourbon-ui/ui.yml",
        "bourbon-ui/css/**/*",
        "bourbon-ui/font/**/*",
        "bourbon-ui/helpers/**/*",
        "bourbon-ui/img/**/*",
        "bourbon-ui/js/**/*",
        "bourbon-ui/layouts/**/*",
        "bourbon-ui/partials/**/*",
    ]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "build",
    srcs = [
        "//compiler:compiler_jvm",
        "//compiler:bourbon",
    ],
    visibility = ["//visibility:public"],
)

test_suite(
    name = "test",
    tests = [
        "//compiler:compiler_tests",
    ],
    visibility = ["//visibility:public"],
)

