#!/usr/bin/env bash
#MISE description="Build and run the native compiler binary"

bazel build //compiler:zeylan

if [ $# -eq 0 ]; then
  exec bazel-bin/compiler/zeylan repl
else
  exec bazel-bin/compiler/zeylan "$@"
fi
