package org.bourbon.compiler;

public enum TokenType {
    LEFT_BRACE, RIGHT_BRACE,
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, COLON, SEMICOLON, BACKTICK, CARET,

    // Single-character tokens.
    DOT, DOT_DOT, TRIPLE_DOT,
    QUESTION, QUESTION_DOT,
    EQUAL, EQUAL_EQUAL,
    TRIPLE_EQUAL, FAT_ARROW,
    PLUS, PLUS_PLUS, PLUS_EQUAL,
    MINUS, MINUS_MINUS, MINUS_EQUAL, THIN_ARROW,
    STAR, STAR_STAR, STAR_DOT, STAR_EQUAL,
    BANG, BANG_EQUAL,
    TILDE, TILDE_EQUAL,
    PIPE, PIPE_PIPE, PIPE_EQUAL,
    PIPE_PIPE_EQUAL,
    LESS, LESS_EQUAL, LESS_EQUAL_GREATER,
    GREATER, GREATER_EQUAL,
    SLASH, SLASH_EQUAL,
    PERCENT, PERCENT_EQUAL,
    AMPERSAND, AMPERSAND_AMPERSAND, AMPERSAND_EQUAL, AMPERSAND_AMPERSAND_EQUAL,

    // Literals.
    IDENTIFIER, STRING, NUMBER,

    // Keywords

    EOF,
    ERROR;
}