package org.zeylan.compiler;

public enum TokenType {
    // Single-character tokens.
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,

    // One or two character tokens.
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,

    // Literals.
    IDENTIFIER, STRING, NUMBER,

    // Keywords
    ABSTRACTS, ALIAS, ASSEMBLY, ASSERT, ASSIGN,
    BREAK, CASE, CATCH, CLASS, CONTINUE, DYNAMIC,
    ELSE, EXISTS, EXTENDS, FINALLY, FOR, FUNCTION,
    GIVEN, IF, IMPORT, IN, INTERFACE, IS, LET, MODULE,
    NEW, NONEMPTY, OBJECT, OF, OUT, OUTER, PACKAGE,
    RETURN, SATISFIES, SUPER, SWITCH, THEN, THIS, THROW,
    TRY, VALUE, VOID, WHILE
}